// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
///import 'firebase_options.dart';
/// // ...
///await Firebase.initializeApp(
///    options: DefaultFirebaseOptions.currentPlatform,
///);
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYo_WccPfcewkfmBJIsncMNrhggkZi6F8',
    appId: '1:646008106934:web:605a5a3b9d0086e02ddb17',
    messagingSenderId: '646008106934',
    projectId: 'ulingo4',
    authDomain: 'ulingo4.firebaseapp.com',
    storageBucket: 'ulingo4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcJxSN4i4YOnwto3H_-gqQDI392LbEzWQ',
    appId: '1:646008106934:android:47bdc8fd5a9e2c442ddb17',
    messagingSenderId: '646008106934',
    projectId: 'ulingo4',
    storageBucket: 'ulingo4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB94HNzppwRNTgmBCffvpXcNrLTs72Zq_w',
    appId: '1:646008106934:ios:e9ef776c0dc71d012ddb17',
    messagingSenderId: '646008106934',
    projectId: 'ulingo4',
    storageBucket: 'ulingo4.firebasestorage.app',
    iosBundleId: 'com.example.ulingoV4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYo_WccPfcewkfmBJIsncMNrhggkZi6F8',
    appId: '1:646008106934:web:3e094dd97a231fdb2ddb17',
    messagingSenderId: '646008106934',
    projectId: 'ulingo4',
    authDomain: 'ulingo4.firebaseapp.com',
    storageBucket: 'ulingo4.firebasestorage.app',
  );
}
